### ISSUE TITLE
Typo on homepage

### ISSUE THREAD

**Issue by BWPanda** [simple-login/website#1]
There's a typo on the homepage:

> What you can you with SimpleLogin

I'm assuming this should be "What you can **do** with SimpleLogin"?

I'm not familiar with static sites, so not sure if simply changing [this line](https://github.com/simple-login/website/blob/master/layouts/index.html#L65) is the way to fix it...

**Comment by nguyenkims** [comment]
@BWPanda sorry for the late reply, somehow I don't get any GitHub notification ... This phrase has been removed from the website :)
