### ISSUE TITLE
Make the description box bigger

### ISSUE THREAD

**Issue by mfmw123** [simple-login/website#10]
Hello,

This is a nice quality of life enhancement to have because on PC the description box is just too small and it's a pain to write longer descriptions.

**Comment by nguyenkims** [comment]
@Beventar can you send a screenshot of how it looks on your screen? On mine, the text area is ok in size so I guess that might depend on the screen resolution.

**Comment by Beventar** [comment]
![image](https://user-images.githubusercontent.com/51784467/150860358-c36a7044-c973-444f-bcac-3f50bec147a0.png)

my resolution is 1920x1080 but i have 1 really long description that i have to scroll to see and edit and when i scroll and click to edit it it just goes back up and i dont know what im typing
