### ISSUE TITLE
[Feature request] logged in sessions

### ISSUE THREAD

**Issue by Beventar** [simple-login/website#15]
Show logged in sessions and be able to revoke them (sign out of them). kind of like the api keys used by mobile apps

it is useful for when a device logged in to an account is lost and u dont want anyone be able to access your account

**Comment by MrMuffinIsTaken** [comment]
This is indeed something that i would like being added to simplelogin. Altho one complaint i do have is that the settings under the settings tab in the web app are just kind of a big mess. So before implementing this, i would recommend they fixed that first. I wish they made it bit more user friendly and changed the layout to something like the following:  

**Alias** / **subdomains** /  **directories** / **mailboxes** /  **domains**  / **developer* / **Settings** 

And then sort the setting tab out like this (with sub menus):

#  **Settings** 

**Account**
**Security**
**Privacy**
**Recovery**
**Billing**
**Referrals**
**API Keys**
**Other**

And then in the security sub menu, they can add a something like the following:

# Active Sessions
Device logged in:
Type: web app login
Location: Republic of seychelles, Victoria
Device: Internet Explorer on Windows XP
IP Address: 192.X.X.1
IPS: Republic of seychelles's best ISP that goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
Host Name: brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.republic-of-seychelles-best-isp.com

This can of course be done without the IP address and host name and can be kept for as long as the session is alive and active for.

**Comment by nguyenkims** [comment]
@Beventar  please create a feature request in https://github.com/simple-login/app/discussions so other people can upvote it too so we can prioritise it :)

**Comment by Beventar** [comment]
This is the link #1098
