### ISSUE TITLE
Time to updated the privacy policy again.

### ISSUE THREAD

**Issue by MrMuffinIsTaken** [simple-login/website#16]
Hey @nguyenkims, i guess it's time to updated the privacy policy again to add the following: zendesk.com, postmarkapp.com, report-uri.com, upcloud.com, nginx.com, ubuntu.com, hstspreload.org, postfix.org, https://upptime.js.org services to the third party services selection and to also mention the CCPA (General Personal Data Protection Law) & LGPD ("General Personal Data Protection Law" aka "Lei Geral de Proteção de Dados Pessoais"). :D

**Comment by nguyenkims** [comment]
@MrMuffinIsTaken we have updated the privacy policy to include zendesk https://simplelogin.io/privacy/

For other services, they are rather devops services and don't deal with user data.

**Comment by MrMuffinIsTaken** [comment]
Fair. You may close this issue now.
