### ISSUE TITLE
Outdated Proton branding

### ISSUE THREAD

**Issue by cYDN48** [simple-login/website#32]
Proton's branding on the SimpleLogin website is outdated in some places. Except for the first point it's just the usage of "Protonmail" or "ProtonMail" instead of "Proton Mail", (or "ProtonVPN" instead of "Proton VPN" in one blog article).

On the main homepage:
- Outdated logo in step 2. of "How it works"
- "Works perfectly with Protonmail" should be "Works perfectly with Proton Mail"

In the Blog:
- [Threat Models: How to Establish One to Protect Your Privacy](https://simplelogin.io/blog/threat-models-how-to-establish-one-to-protect-your-privacy/)
- [10 Free Ways To Protect Your Privacy Online](https://simplelogin.io/blog/10-free-ways-to-protect-your-privacy-online/)
- [Getting Started with Email Forwarding Services](https://simplelogin.io/blog/email-forwarding-declutter-inbox/)

In the documentation:
- [Troubleshooting](https://simplelogin.io/docs/getting-started/troubleshooting/#create-a-protonmail-filter)
- [One-click unsubscribe](https://simplelogin.io/docs/getting-started/one-click-unsubscribe/)
- [Add a new mailbox](https://simplelogin.io/docs/mailbox/add-mailbox/)

A few more can be found [here](https://github.com/simple-login/website/search?p=1&q=proton).
On top of that I found outdated logos in this repo, like [this](https://github.com/simple-login/website/blob/master/static/email-service-logos/protonmail.svg) and [this](https://github.com/simple-login/website/blob/master/static/blog/mailbox-protonmail.png), but I couldn't find where they're being used on the website.

**Comment by nguyenkims** [comment]
@cYDN48 these articles were created before the Proton rebranding happens indeed. Can you please create a pull request to update those?

**Comment by cYDN48** [comment]
Just noticed that the documentation is in another repo. I'll be opening a Pull Request there as well to update stuff

**Comment by cYDN48** [comment]
The pull request in the documentation's repo has been created. Now I just need your help to finish them, so they can be merged 😃

**Comment by nguyenkims** [comment]
@cYDN48 thanks for the PR, I just merged them and deployed.

**Comment by mfmw123** [comment]
There's also the old Proton Mail branding in the blog "Introducing PGP". It's an illustration.
