### ISSUE TITLE
Consistency in platform icons on the homepage

### ISSUE THREAD

**Issue by mfmw123** [simple-login/website#35]
On the homepage, below the app/website/extension showcase, the platform icons like Chrome, Firefox, App Store etc. are inconsistent.
The browsers and App Store are icons while Google Play Store and F-Droid are badges (or in F-Droids case it's more a text next to the icon).

So replace Google Play Store badge and F-Droid icon with text to just icons so it's consistent.

**Comment by nguyenkims** [comment]
This has been updated in the latest version. You might need to empty cache in order to see the changes though.
