### ISSUE TITLE
Unable to resolve simplelogin.io

### ISSUE THREAD

**Issue by obeho** [simple-login/website#4]
I don't know since when this error is being shown, but I'm assuming even if I send an email to hi@simplelogin.io, it wouldn't be able to deliver, so I'm creating an issue here. Across ISPs and resolvers this error is being shown. Please look into this.

TIA

@nguyenkims @saifelokour

**Comment by saifelokour** [comment]
Hi @obeho, could you please clarify what the error is, and where you're getting it? A screenshot would be helpful.

**Comment by nguyenkims** [comment]
@obeho we still receive emails at hi [at] simplelogin.io.

**Comment by obeho** [comment]
Thanks @nguyenkims for the info. Now, the issue is resolved.

@saifelokour, the error was just return of NXDOMAIN while resolving the DNS for `simplelogin.io` so it must've been non-existent/offline for a few hours.
