### ISSUE TITLE
Replace PrivacyTools References with Privacy Guides

### ISSUE THREAD

**Issue by jonaharagon** [simple-login/website#6]
The PrivacyTools team has archived the privacytools.io GitHub project and is moving to @PrivacyGuides, for various reasons. The announcement can be found on Reddit here: https://www.reddit.com/r/PrivacyGuides/comments/pnhn4a/rprivacyguides_privacyguidesorg_what_you_need_to/

---

There are references to PrivacyTools at https://github.com/simple-login/website/blob/3d890c53de25ab3f68e89f4a6dc8d62b58d57187/layouts/index.html#L96-L97 and https://github.com/simple-login/website/blob/00fa27be8c677af732cc6c5e2136051e03dcf79f/data/faq/tech.yaml#L3 that should be replaced with https://www.privacyguides.org/providers/email/#cloaking and https://www.privacyguides.org/software/file-sharing/ respectively.

Here's a replacement logo which can be used on light backgrounds:

![privacy-guides-200x200](https://user-images.githubusercontent.com/3637842/134086035-74c56b4f-3293-42a3-ae1f-083fe85b7024.png)

"Privacy Guides" branding does have a space in it.

---

Thanks! Let me know if you have any questions.

**Comment by nguyenkims** [comment]
@jonaharagon thanks for the info! The website has been updated in https://github.com/simple-login/website/commit/4fe06b97ed349977051f7fd6035a419abb2b98ab :)
