### ISSUE TITLE
Is any help needed with the translation project of the site?

### ISSUE THREAD

**Issue by therealmrmuffin** [simple-login/website#8]
So i saw that the simplelogin website is available in French and i wanted to know if i would be able to provide translation services to simplelogin for free?

**Comment by MrMuffinIsTaken** [comment]
@nguyenkims just mentioning you to make sure you see this Issue.

**Comment by nguyenkims** [comment]
@MrMuffinIsTaken thanks a lot! We haven't finalised the setup for the translation. We'll make sure to ask for help when the translation setup is ready :).

**Comment by MrMuffinIsTaken** [comment]
Alright. I'll be waiting! :D

**Comment by therealmrmuffin** [comment]
@nguyenkims still need help with this. I might close this issue if you don't need my help with this.
