### ISSUE TITLE
Change "More" button to "Less" when alias card is expanded

### ISSUE THREAD

**Issue by lazycalcium** [simple-login/website#9]
Currently, when a user clicks the "More" button on an alias card on their dashboard, it expands to show additional information, but they still have to hit the "More" button to close it back up. Can the text be changed to "Less" when opened?

![screenshot](https://user-images.githubusercontent.com/97489564/148870118-3e861610-5349-49fb-8a01-f915d47515f2.png)

**Comment by nguyenkims** [comment]
This is indeed a good idea. We just updated the latest version and the button should now behave correctly.

**Comment by lazycalcium** [comment]
Thanks for the quick fix @nguyenkims SL is awesome.
