### ISSUE TITLE
Simplelogin.io is extremly slow

### ISSUE THREAD

**Issue by HyperCriSiS** [simple-login/website#95]
Hi,
Simplelogin.io is mostly extremly slow.
Also I am getting many timeouts.
The site is often not reachable for several minutes. 

Do you currently have issues with the servers? 
According to your uptime monitor, the response times are really terrible.

Thanks and regards
Hyper

**Comment by nguyenkims** [comment]
Hi we don't see any abnormal activity with SimpleLogin in the last 7 days.

**Comment by HyperCriSiS** [comment]
It seems fixed now. There was definitely something wrong. I had so heavy timeouts, that the site was unusable for days.
Response times are still 400-750ms, which still seems quite high. But no timeouts anymore. :+1:
